### ISSUE TITLE
Fails to validate some DK iban

### ISSUE THREAD

**Issue by minlau** [jacoelho/banking#45]
DK0206715394960066 iban is considered invalid. Error I receive is: `incorrect checksum: validation error`

```
package main

import (
	"fmt"
	"log"

	"github.com/jacoelho/banking/iban"
)

func main() {
	err := iban.Validate("DK0206715394960066")
	if err != nil {
		log.Fatal(err)
	} else {
		fmt.Println("valid!")
	}
}
```
For example:
https://bank.codes/iban/validate/ or https://github.com/jbub/banking considers it valid.

Library version:  v1.1.37 (latest as of now)

Bonus: during testing of this lib I found that from 350k unique ibans 3500 were falsely invalid.

**Comment by jacoelho** [comment]
Thank you for reporting. 

Sounds like an issue calculating the mod97-10, going to investigate.

**Comment by minlau** [comment]
Just tested it on 350k ibans - works good now.
Sorry, but iban set is not public.
