### ISSUE TITLE
Iranian IBAN support

### ISSUE THREAD

**Issue by ccoVeille** [jacoelho/banking#62]
Someone opened an issue on supporting  Iranian IBAN on https://github.com/almerlucke/go-iban project

I made some searched and gathered some information

26 characters
IR + 24 digits

Some sources:

https://iban-analyzer.com/iban-countries/ir

https://www.iban.com/structure

Structure 3 digits for the bank apparently

https://github.com/rghorbani/iran-sheba/blob/master/index.js#L292

Validation examples:

https://github.com/rghorbani/iran-sheba/blob/master/index.js#L308-L328

https://github.com/RezaOptic/irvalidator-python/blob/develop/irvalidator%2Fiban.py

classic rule apparently, to be checked

_Originally posted by @ccoVeille in https://github.com/almerlucke/go-iban/issues/3#issuecomment-2466657528_

Are you interested in supporting Iranian IBAN in your lib?

**Comment by ccoVeille** [comment]
My request is about knowing if you are interested

I can open a PR then.

**Comment by jacoelho** [comment]
Thank you for your research.

Looks like Iran is not in the official swift iban registry, this library only contains countries in the registry, until that happens it will not be supported.

Feel free to fork if you want to support it, you can update docs/registry.yml and generate the code.

**Comment by ccoVeille** [comment]
I'm fine with your reply.

Thanks

**Comment by ccoVeille** [comment]
For anyone who find this issue later, here are some alternative projects where the Iranian IBAN might be supported

- https://github.com/go-pascal/iban/issues/10

- https://github.com/almerlucke/go-iban/issues/3
